name: ${name}
version: ${version}
api-version: 1.13
author: WhiteCat
main: cf.catworlds.dynamicspigotsetting.MainClass
commands:
  DynamicSpigotSetting:
    description: main
    aliases: dss
    usage: -| 
      /<command> <item|exp|> radius
      /<command> reload
    permission: plugin_template.test
permissions:
  dynamicspigotsetting.test:
    default: op